services:
  - type: web
    name: claims-management-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: claims-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.6

databases:
  - name: claims-db
    databaseName: claims_db
    user: claims_user
    plan: free